imports:
    - { resource: tables.yml }

services:
    tmbackoff.knowledgebase.listener:
        class: tmbackoff\knowledgebase\event\listener
        arguments:
            - @auth
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }

    tmbackoff.knowledgebase.admin.controller:
        class: tmbackoff\knowledgebase\controller\admin_controller
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @controller.helper
            - @log
            - @request
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
            - %tables.categories%
            - %tables.articles%

    tmbackoff.knowledgebase.main.controller:
        class: tmbackoff\knowledgebase\controller\main_controller
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @controller.helper
            - @request
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
            - %tables.categories%
            - %tables.articles%

    notification.type.article_in_queue:
        class: tmbackoff\knowledgebase\notification\article_in_queue
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }
